import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./layout.module.scss";
import "./globals.css";
import BrandIcon from "@/components/atoms/brand-icon";
import ProfileDropdown from "@/components/melecules/profile-dropdown";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.header}>
          <BrandIcon />
          <ProfileDropdown />
        </div>

        {/* content */}
      </body>
    </html>
  );
}
