import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./layout.module.scss";
import "./globals.css";
import BrandIcon from "@/components/atoms/brand-icon";
import ProfileDropdown from "@/components/melecules/profile-dropdown";
import { MantineProvider } from "@mantine/core";
import { FC } from "react";

interface RootLayoutProps extends Readonly<{
  children: React.ReactNode
}> {}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

const RootLayout: FC<RootLayoutProps> = ({children}) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider>
          <div className={styles.header}>
            <BrandIcon />
            <ProfileDropdown />
          </div>

          {/* {children} */}
        </MantineProvider>
      </body>
    </html>
  );
}

export default RootLayout